---
#########################################
# options for knitting a single chapter #
#########################################
#output:
#  bookdown::pdf_document2:
#    template: templates/template.tex
#  bookdown::html_document2: default
#  bookdown::word_document2: default
#documentclass: book
bibliography: [bibliography/references.bib]
---

# Ethnography Based on In-Situ Observations within an Adult Intensive Care Unit and Emergency Department {#chapter-6}

\adjustmtc
\markboth{6. Ethnography}{}

<!-- For PDF output, include these two LaTeX commands after unnumbered chapter headings, otherwise the mini table of contents and the running header will show the previous chapter -->

In the preceding chapters, I have presented empirical results from experimental studies conducted during this DPhil that aimed to investigate confidence and information seeking during medical diagnostic decisions. These studies have been designed to emulate aspects of the diagnostic process as it is carried out in real medical practice, such as investigating how the differentials being considered evolve over time with more information. I also aimed to use patient cases that were representative of the cases that clinicians encounter in real medical practice. In addition, I used a virtual reality methodology in the study presented in Chapter 5 to simulate how patients can improve or deteriorate over time depending on the administration of treatment. Through this work, I believe that understanding the cognitive mechanisms of diagnoses has implications for real medical practice. I understand however that by using controlled experimental paradigms, I abstract away certain practicalities of real medical practice that can also impact diagnostic confidence and information seeking.

\
In order to aid the judgement of this thesis's applicability and ecological validity as it pertains to medical practice, I conducted in-situ observations using a rapid ethnographic approach [@vindrola-padros_quick_2018] as part of a clinical service evaluation (which is based on observing current healthcare service rather than making new knowledge or interventions, @twycross_service_2014). I utilised a grounded theory approach for qualitative analysis [@smith1995], meaning that I used observations to identify individual cases/episodes that could be used to build theoretical concepts of how clinicians make decisions. These were conducted in two different medical environments: Adult Intensive Care (AICU) and the Emergency Department (ED). These two environments were chosen as they tend to exhibit differing instances of uncertainty. There is a higher level of uncertainty in ED given it is the first port of call for a patient who presents as very unwell, whilst in AICU, there is usually at least a baseline set of investigations that have already been done for a patient. In addition, while patients can deteriorate quite rapidly in both settings, AICU tends to provide more immediate access to additional expertise (e.g. microbiology, pharmacists, physiotherapy). The two environments also differ by patient inflow, given that ED can be busier and more uncontrollable (given it is very rare for an ED to stop admitting new patients), whereas in AICU there is a set number of beds available and patients can be transferred to other hospitals if capacity is full. To summarise, in AICU, patients have usually been staying at the unit for an extended period of time, which results in a lot of information being already available on a patient, though there remains uncertainty about the future trajectory of a patient. For ED however, patients may present with much less information available to clinicians beforehand, with uncertainty being more analogous to our experimental studies in that clinicians are more likely to experience diagnostic uncertainty. These two contexts then provide quite different examples of what information may be available on a patient and different types of uncertainty on the part of clinicians.

\
I conducted observations within the AICU and ED at the John Radcliffe Hospital in Oxford. They were conducted after the successful application for an Observer contract within the OUH (no other hospitals were visited. The contract makes it clear that “Observers are appointed solely for the purposes of observing practice at the Trust. Observers are not authorised to advise Trust staff on the treatment of patients, teach clinical procedures, assist with laboratory work or take part in any procedure involving patients (e.g. ordering tests, taking specimens)”. Observers are authorised to shadow a staff member, and to not enter areas of the hospital unaccompanied. Authorisation for observation was granted on September 13th 2023 (Reference Number: 462722). Observations were conducted during the morning handovers and ward rounds in AICU and during both day shifts and night shifts in ED. This totaled 12 hours of observations in AICU and 15 hours of observations in ED. These observations took place between December 2023 and September 2024. Observations during shifts were captured using diary/field notes and then synthesised for this chapter. Observations during shifts were conducted with permission of the clinical lead and staff involved during the shift beforehand with the pre-eminent purpose of observing conversations between staff members. For interactions with patients, the staff members being shadowed asked the patient for permission for the observer to be present before proceeding. If the patient did not give consent or was not in a state to give consent (which is especially common in AICU), the interaction was not observed.

\
Observations were focused on how clinicians interacted with each other rather than the particulars of the patient. No identifying information about patients or clinicians was recorded. In this thesis chapter, I reflect on what clinicians’ sources of uncertainty are and how they diagnose patients alongside their colleagues, but do not make generalisable or transferable inferences based on my observations. We used the MRC and NHS Health Research Authority “Defining Research” tool (<https://www.hra-decisiontools.org.uk/research/docs/DefiningResearchTable_Oct2022.pdf>), and the work was defined as “service evaluation”, as we are not testing any interventions with patients, interfering with clinicians in terms of their practice or using the observations to make any recommendations of changes to patient care. We have submitted the protocol to the OUH Ulysses platform as a Service Evaluation Project (Ref: 9929).

\
In this chapter, I use these observations as a naturalistic grounding to discuss this DPhil’s strengths and limitations, as well as how the scenarios I emulated in this work do also come up in everyday medical practice. I start with a discussion of reflexivity from a personal and contextual standpoint to discuss the perspective from which the work stems from (using recommendations on discussing different types of reflexivity from [@olmos-vega_practical_2023]). I then introduce the medical settings within which the observations were conducted, noting similarities and differences between them in terms of the work that clinicians do. Following this, I present instances of this DPhil’s key research interests on confidence, information seeking and differential evaluation as they arise in these medical environments. Finally, I evaluate the ecological validity of this DPhil in terms of the aspects of these medical environments that are captured or not by this DPhil and its empirical studies. These reflections contribute to the Overall Discussion section by grounding the strengths and limitations of the work in observations of medical practice.

\
I considered the following questions during the observations:

-   **How do clinicians communicate certainty/uncertainty to each other and to patients within healthcare environments?**
-   **What types of clinical/patient situations tend to result in instances of uncertainty?**
-   **What aspects of the hospital environment support/inhibit the information seeking by clinicians when making decisions?**
-   **How often do clinicians evaluate multiple diagnostic differentials for a given patient?**

## Reflexivity

Reflexivity is the notion of actively reflecting on how a researcher's positionality (i.e., a researcher’s own experiences and perspective) impacts the research process [@lazard2020]. The concept of reflexivity challenges the idea that knowledge production is objective and independent of the researcher producing it [@berger2015], which is especially pertinent for qualitative research. Considering reflexivity within the ethnographic process allows researchers to be aware of their own biases and how they might affect the research process, as well as allowing for greater transparency for other researchers.
\

I started research on medical decision making during my MSc degree in Human-Computer Interaction (which is a subfield of Computer Science, and not inherently related to the study of Medicine) from University College London during a thesis project looking at perfusion data visualisation during paediatric cardiac surgery. As part of this project, I conducted in-situ observations and interviews within a children’s hospital. During the same degree, I also conducted interviews for a project to design a visualisation tool for monitoring the flow of patients in and out of AICU. Both of these projects positively contributed to my interest in studying medical decisions in more detail during my DPhil. I myself do not come from a background in medical training/education. This affects the lens through which the data are observed and analysed, because the observations are synthesised in such a way that is not in line with the researcher’s own experiences. I also possess limited first-hand experience as a patient within the healthcare system, aside from interactions with general practitioners (GPs) for non-serious health conditions. My own perspective as a researcher stems from a desire to study situations that are based on real-world decisions with high impact and stakes, such that I hope for my own research to have an impact (however small). My experience conducting this research has reshaped my perspective on medical decisions and healthcare as a whole, via my collaboration with several clinical faculty/researchers and through the observations of clinicians at work.

\
From a contextual perspective, this work (as well as the observations presented in this chapter) was conducted in the UK, with a particular focus on medical students and staff based in Oxford’s John Radcliffe Hospital. Public healthcare in the UK is conducted under the governance of the National Health Service (NHS). Over the course of the DPhil, the NHS was a constant topic for reporting by UK news outlets, given the consequences for healthcare in the wake of the global COVID-19 pandemic and national strikes by healthcare workers due to pay disputes and understaffing. As noted in the systematic scoping review, contextual factors have been shown to impact clinician confidence. The specific context of this work (and the observations presented in this chapter) should not be considered as representative of healthcare as a whole (either in other parts of the UK or in other countries). It is likely however that the focus on the cognitive psychology of diagnoses allows for insights that have aspects of generalisability to other medical contexts.

## The Adult Intensive Care Unit

AICU units are "specialist hospital wards that provide treatment and monitoring for people who are very ill" (Intensive Care Society). Clinicians and nurses in AICU monitor patients' health and support their bodily/organ functions until they have recovered. AICU can be hugely beneficial for patients by providing urgent care for them in hopes of aiding their road to recovery. Patients then tend to move elsewhere in the hospital, such as the main ward or to theatre for surgical intervention. AICU sits outside of other medical subdisciplines, and are among the most 'holistic' clinicians in a hospital. This is because they tend to consider a collection of physiological systems rather than a single one (i.e. unlike a neurologist considering the brain, or a gastroenterologist considering the gut), which makes them relatively unique among other clinicians. It is very frequent that individuals working in AICU collaborate with other staff by bringing in external advice from other departments in the hospital, such as Rheumatology, Neurology, Surgery, Vascular or Trauma. AICU is then a department that involves many individuals, both from within and outside its remit. Quickly and temporarily formed teams then have to collaborate on a patient and align their mental models. It is very common for teams of individuals to work together despite having little to no prior experience with each other. In brief, AICU is usually a point of transition for patients within their medical pathway through the hospital, with other departments using the service provided by AICU and supporting ongoing care for patients after they are discharged from AICU, or patients failing to recover from their illness, and dying in AICU.

\
A frequent concern, on a daily basis, that consultants within AICU have to contend with involves monitoring AICU capacity in the present and in the future. Every AICU has a limited capacity in terms of the number of beds available and hence the number of patients who can be cared for at any given time (this was 22 beds for the unit observed). These capacity issues are of course related to actions of those in AICU but are also inexorably linked to wider environmental factors. This includes funding for increased AICU capacity and staffing as well as structural or technological issues within the hospital and region/NHS Trust as a whole. During one of our observation sessions, the unit was understaffed with respect to guidance on staffing ratios need to manage the number of patients and their acuity/severity levels. A consistent source of pressure for ICU staff is a shortage of staff with the skills and experience to guide care of an increasing number of patients, resulting in more work for staff and lower patient turnover to free up capacity [@page_strategies_2024].

\
A patient is able to leave AICU and hence free up a bed if they either improve enough to transition to another unit in the hospital or if they unfortunately die in AICU. However, because AICU is a patient support unit, patients can also find themselves in the unit for a longer period with very slow improvement or deterioration. As a result, patients can sometimes stay in AICU for weeks or even months. Clinicians and nurses in AICU have to balance what they can realistically do for a patient within their remit whilst being cognizant of the longer-term outcome of the patient. This is best summed up by one clinician who said during observations: “there is balance of what we can do and what is kind [to the patient].”

## The Emergency Department

The Emergency Department (ED, sometimes referred to as Accident & Emergency or A&E) is a part of the hospital that is designed to deal with "the prevention, diagnosis and management of acute and urgent aspects of illness and injury" [@noauthor_about_2024]. Although some patients may be admitted from other hospitals (if they are especially serious), most patients are individuals who have walked in to report their symptoms. An issue that patients who walk in presents is that a lot of patients may report to ED with non-serious conditions (e.g. a migraine). This demands time from clinicians that could otherwise be allocated to more serious patients. Whilst observing a registrar in ED, they remarked that they tend to see patients quickly and use pattern recognition so that they can quickly identify patients who require more urgent care. The ED observed was spread out over multiple sections, broadly separating patients into minor and major cases. Patients report to a reception area, where their details are recorded and their case is triaged (i.e. they are seen by a nurse who determines their level of urgency based on a validated triage scoring tool). They then stay in a waiting area until they are called to be seen by a clinician. Due to the number of patients who attend and the time it can take for certain tasks to be completed (e.g. getting test results, completing a patient’s discharge documentation), patients may have to wait for variable and sometimes extended periods of time between arrival, triage and review by a clinician. After seeing the patient, clinicians in ED have a few possible options of how to proceed. If the case is not overly serious, patients could be sent home with some medical advice, a prescription for medication and/or safety netting (i.e. advice to return if the symptoms persist or worsen). If the case is more serious, patients may be admitted into the ED and given a bed for further treatment. Patients may be admitted to ED for initial assessment and initiation of treatment, but then go to a bed elsewhere in the hospital (depending on the time that this transfer process takes). Patients could also be transferred to other departments or hospitals for further observations or treatment.

\
The key decisions for clinicians in ED then involve forming an assessment of how serious a patient's condition is and whar the best course of action is to take for their care. Given that the turnover of patients can be relatively high in ED, patients have to be seen to quite quickly in terms of their initial assessment and suitability for admission into ED (and allocation of a bed). Whilst a patient is then in ED, diagnostic decisions are made and reevaluated to maintain an up-to-date understanding of the patient's condition and their current course of treatment.

## Commonalities in Decision Making Between AICU and ED

I now report the observed commonalities between AICU and ED, firstly detailing aspects to do with the overall function of these departments. I then focus on aspects related to this thesis’s main research areas on confidence, information seeking and differential evaluation.

\
Firstly, both departments are involved in a large degree of coordination with other departments and other hospitals. Part of AICU’s coordination with other departments/hospitals consists of incoming requests for the admission of new patients. This could include a patient who has experienced a complication during surgery or a patient who has been admitted from an outside hospital in need of urgent care. Capacity is constantly at a premium and it is at the forefront of an AICU consultant’s thinking. Ideally, the unit should be able to operate with a spare buffer capacity of one or two beds in case of an emergency. Spare capacity is fairly rare in practice however, as it can be due to factors outside of the control of the clinicians in AICU, such as funding and available equipment/facilities [@gooch_icu_2014; @murthy_intensive_2015]. AICU can hence act as a central coordinator of several decision makers who are involved with a particular patient’s care, calling specialists for relevant issues and expertise. AICU clinicians have primary responsibility for patients whilst they are in the unit. As one clinician put it, “someone who has trauma is no longer Trauma’s responsibility.” A big part of this coordination then is knowledge of the hospital's departmental structure, in terms of capacity and available expertise across the various hospital departments. For ED, there is a similar coordination with other departments in terms of seeking advice from other subdisciplines and with other hospitals, for example when transferring patients.

\
As an example, one observed patient in ED had chemical burns all over their arms. After receiving treatment and cleaning of the wounds, the patient reported pain and tingling in the arms. This suggested a possibility of compartment syndrome, where the pressure around the muscles can cause restricted blood flow. If left untreated, the patient may require surgery (known as a fasciotomy) to relieve the pressure. In order to clarify this diagnosis, the ED registrar sought the opinion of a consultant in the Plastic Surgery department. This was important, because the patient was to be transferred to a different hospital, which did not have capacity for the patient until the next day. If however the patient did have compartment syndrome, the other hospital would urgently free up capacity to admit the patient as soon as possible. Here in this example, it can be seen how ED involves both an external department and another hospital in the decision-making process, similar to AICU.

\
The key decisions being made are fairly similar in both settings, in that they both involve acutely unwell patients, though at different stages in their care pathway. A patient who is admitted into ED may end up in AICU later on if their condition worsens. However, most patients in AICU are, or have been, critically unwell, whereas patients in ED display much more variance in the severity of presentations (e.g. patients arrive at ED seriously injured after a motor vehicle collision or may present with a simple viral illness). Both settings are then about assessing patient severity and likelihood that a condition will improve or worsen, with a suitable course of treatment recommended and administered by clinicians to aid the patient.

\
Another similarity between the two settings is in terms of documentation. A key activity observed during shifts in both ED and AICU was documenting the latest developments with the patient. The ‘record keeping’ for patients took up a significant portion of the clinicians’ time during the observed shifts. This took the form of a digital, centralised "electronic patient record" (EPR) where clinicians recorded the latest observations of the patient and the current set of actions to be taken. Other information is also recorded here, such as test results and scans. Such a centralised documentation platform is useful for handover between staff rotating on and off shifts, such that healthcare professionals can rapidly access notes and results recorded by the preceding teams with the aim of making the transition of care between medical staff easier. If such documentation is not done thoroughly and clearly, this can create a source of confusion and uncertainty for staff currently caring for a patient, as they may be unsure about what care/tests were previously carried out. This should be noted as a specific facet of this hospital, as other hospitals in the UK (let alone in other countries) do not have computerised platforms to record all information pertaining to each patient. Different departments also utilise differing EPR systems/software without any overarching standardisation for their design, leading to challenges with finding information (especially when such interfaces are not intuitive for users). Many hospitals make use of simple paper documentation instead, which is more likely to lead to situations of past documentation for a patient not being available (due to such paper documents not being scanned and getting lost). When a clinician first sees a patient during their shift, the starting point they have in terms of a patient's medical history is partially dependent on the documentation available from those clinicians who had previously treated the patient. Some patients may also bring documentation they had received from other hospitals to aid the clinician in their initial understanding of the patient’s condition. Taken together, the act of recording the patient’s trajectory throughout their time in hospital is useful for ensuring a smooth transition of care to other staff, departments and hospitals.

## Uncertainty

Just as there are both commonalities and differences in the broad functioning of AICU and ED, there are similarities and differences specifically relating to how diagnostic uncertainty arises in the two departments, as it can manifest differently within AICU and ED. In both departments, the condition of a patient can change fairly quickly, for example a patient presenting with what is initially thought to be a straightforward viral infection can develop fulminant sepsis within hours. This is why, at least in the departments I observed, there is a regular cadence of communication. This comprises a morning handover, where the consultant during the night shift hands over to the day shift consultant and reports patient developments that occurred during the night. In AICU, clinicians performed morning, afternoon and evening ward rounds, during which the consultant visits each patient bed to receive updates on the patients by their nurses and (when possible) talk to the patient. During these ward rounds, the consultant will collaborate with the registrar, nurses and any individuals from other relevant departments to formally record an assessment of the patient and recommend a short-term action plan to be taken for that patient and to be coordinated with the attending nurses. This includes a formal assessment of whether the patient is clinically fit enough to be discharged (or if the department is not able to do much more for the patient given their capabilities and facilities). In ED, it was common for staff to check their understanding and treatment plan for the patient with the registrar (a doctor in the middle of their training, after being a junior doctor but before becoming a hospital consultant) for that shift. These discussions between the clinicians and the registrar happened fairly regularly, such as when there was an update with the patient or a new test result. In both settings (ICU and ED), clinicians tended to avoid making decisions on their own, instead adopting a collaborative approach to decision making.

\
In summary, because the nature of a patient’s condition can change quickly, it is important that healthcare professionals communicate regularly to ensure good situation awareness [@endsley_toward_1995], which is considered the combination of perceiving a situation, accurately comprehending it and projecting its future state. Diagnostic thinking is expected to be dynamic in a setting like Emergency Medicine, which has been thought of as a complex, dynamic combination of many interconnected systems on the clinician and organisational level [@widmer_complex_2018]. Diagnosis is a constantly evolving process as the understanding of the patient changes with time (even without considering new information or tests being made available about the patient). Uncertainty can arise not just from the patient's present condition but their condition in the future and the state the healthcare department (i.e. in terms of capacity, staffing etc) in the future in terms of its capacity to handle the care of patients.

\
Before discussing how diagnostic uncertainty varies between AICU and ED, it is important to explain how broad diagnosis is. As became clear through observations, diagnosis is multi-faceted and can take multiple forms. Diagnosis is often not simply about identifying the condition that the patient has. It also involves identifying how severe the condition is, which pathophysiological system(s) is/are driving the symptoms, and the likely development of the condition over time. In AICU, there is usually a lot of information already available on the patient as they have likely already been admitted elsewhere in the hospital (in another department) prior to arriving in AICU. Hence, there has already been a recording of medical history and recent test results, meaning that there is usually not a lot of uncertainty about what condition the patient has. Rather, the real uncertainty stems not from the patient’s condition now, but the patient’s condition in the future, such as in 24-48 hours’ time. An AICU consultant may consider the following questions:\

-   How much worse 'could' this patient's condition become?
-   What realistic milestones/goals can we set for this patient’s recovery plan?
-   Is the patient ‘wardable’? (i.e. is the patient well enough to be discharged from AICU and sent to the main hospital ward for continued care that is not as acute)

\
Making decisions about the current and future capacity of AICU (and ED) is hence extremely complex, as it involves an understanding of each patient’s condition not only in the current moment but in the future. Essentially, how likely is the patient to improve or deteriorate? There is a projection of future state that occurs (as per the parlance of research on Situation Awareness: @endsley_toward_1995) that occurs at several organisational scales. There is projection at the individual patient level, where clinicians forecast how well/unwell a patient will be in the short- or long-term future. This projection involves looking at the trend of treatment and what the upcoming milestone/endpoint for that patient might be. Milestones for patients could include simply getting the patient to eat solid food again or get up from their bed, or it could be tied to specific patient parameters (e.g. raising oxygen levels). Such projection also occurs at the unit/department level, as the combination of each patient’s situation produces an overall picture of the unit’s available capacity to admit new patients. Finally, the projection can also take place over the entire NHS trust/region. During observations, the start of a morning AICU shift began with the announcement that there was ‘no capacity across the Trust’, meaning any incoming requests from other departments to admit patients would have to be refused (at least initially).

\
In ED however, the situations that clinicians encounter are much more about formulating an initial working diagnosis to guide subsequent care. This is because patients are, for the most part, visiting the hospital for the first time for this particular condition. The patient’s visit may also be the first point of contact with the healthcare system for the current ‘episode’ of a chronic/recurring condition. As a result, there may not be the same recording of information available on the patient as there is in AICU. This relative absence of available information leads to higher initial uncertainty about a patient's condition when compared to AICU. Hence, initial information seeking is important in ED to develop a working assessment of the patient’s condition. Information seeking is directly affected by the initial uncertainty of a patient however, as the receipt of information requires an understanding of the patient for contextualisation. For instance, recording the heart rate of a patient requires, in order to interpret it, an understanding of what is considered a 'normal' heart rate and rhythm for that patient.

\
The aforementioned ‘projection of future state’ is important in ED, as clinicians aim to see serious/urgent patients as soon as possible. Much like AICU, there is a capacity of patients, both in terms of available beds (if needed for the patient) and in terms of staffing. The observed ED aimed to see all patients within a few hours and if some patients require more attention, this affects the allocation of attention to other patients. This is why the registrar had mentioned seeing patients quite quickly, such that severe patients/cases could be identified sooner in order to be prioritised (there are standardised tools available for such triaging of patients, @noauthor_about_2024).

\
In both settings, clinicians had to formulate a trajectory for where the patient would go when they leave the department and what care is provided afterwards. If patients are sent to a different part of the hospital, this could reflect either an increase (e.g. moving from ED to AICU) or decrease (e.g. being discharged so that the patient can go home) in the patient’s severity. Clinicians were required to document this discharge process, in terms of where the patient was to go next and why. Discharging a patient may also require ‘safety netting’ to be put in place, which is where a clinician discusses with, and usually provides written guidance to, the patient and/or their next of kin about what to do if the symptoms recur or worsen in the coming days/weeks. This could include getting over-the-counter medication, visiting their GP or coming back to the hospital again. This safety netting process also includes developing an understanding of social or environmental factors that may have contributed to the patient’s condition. In ED, there were a few examples of elderly patients who were recommended home care visits for safety-netting purposes. There was also one example of a patient who was at risk of self-harming (which had brought them into ED in the first place) again, requiring thorough safety-netting to reduce the likelihood of this happening.

\
This projection of the patient’s future trajectory is a complex task and is in line with Situational Awareness research on taking one’s current understanding of a situation to forecast future outcomes [@endsley_toward_1995]. As a result, there is a different type of uncertainty that can be seen here which has not been explored as much in this DPhil. This assessment of the patient's future state can be prone to biases, as @graz_prognosis_2005 found in their research on surgeons, who tended to overestimate the improvement in patients' quality of life and recovery after their operation. Not only then do clinicians experience uncertainty over what condition a patient may have in the present moment but also what their condition may look like in future (particular for long-term/chronic conditions that extend well beyond the patient’s time in hospital). In the observed ED, if a patient revisited the hospital with the same symptoms within 24 hours of being discharged, this would be counted as a ‘failed discharge’ and would be recorded as a key metric for the hospital/NHS trust’s performance. Hence, the uncertainty about the patient’s trajectory is one with practical consequences.

\
A final ancillary point on uncertainty is its effects on patients in addition to clinicians. Patients are sometimes at the hospital for an extended period of time without a clear diagnosis or understanding of why they are experiencing the symptoms they have. Experiencing long-term/chronic or recurring conditions is a source of major stress for patients (and their next of kin), especially without a clear path to recovery [@meyer2021]. This came across in observations: one patient, for example, had already been to the hospital twice during the same year with recurring episodes of extreme fatigue and losses of consciousness. They lamented the fact that on previous occasions, clinicians were not able to identify a diagnosis for their condition. This underscores another aspect of diagnostic uncertainty and why it is important for future study: the impact that it has on patients in terms of their mental (as well as physical) wellbeing. The lack of closure given by a definitive diagnosis can cause ongoing distress to patients and next of kin, and can even affect patients' trust in clinicians [@bontempo2023]. Without a clear diagnosis, patients often do not have a clear trajectory in terms of their future treatment, which necessitates clear communication strategies from clinicians when they explain their diagnostic thought process to patients [@dahm2023].

## Information Seeking

With regards to information seeking, clinicians in both settings were reliant on notes recorded by other clinicians. In particular, given that consultants and staff rotate their shifts, several clinicians may have a hand in the treatment and care of a single patient. Clinicians frequently record information on the actions and development of that patient during their shift. This means that in order to ensure smoothness in transitioning between clinicians, a clinician has to record information clearly such that the clinician on a given shift understands what took place during the previous one. Not recording information clearly can result in uncertain and inefficient situations. For instance, if a clinician does not record that a CT scan has been requested for a patient, a future clinician may request a second redundant scan. In addition, a future clinician should know if a patient has already been given fluids (and when they were last administered) such as to not overload the patient. Clinicians were observed to vary in how detailed their reports/documentation of patients were, with some taking more time to record patient developments in a lot of detail. Due to preceding clinicians being less assiduous in their record-keeping, there were observed to be delays caused by the clinicians currently caring for patients lacking clarity on what had happened during previous encounters with the patient.

\
A key aspect of information seeking in medical environments is that information can vary in their availability and ‘time cost’. A clinician who was previously treating a patient can provide important information and context to another clinician who is currently caring for a patient. When consulting another clinician, they may be from another department and be able to provide a different, useful perspective on a patient. However, a clinician with required expertise may not be available to provide their opinion when needed, as they may be preoccupied with other patients. Departments may have specialists (e.g. an Ear, Nose and Throat (ENT) specialist) who do rounds of the hospital, but are not always present to provide assistance. When coupled with the rotation of staff, with different levels of experience with certain types of patients or procedures, the nature of the department’s expertise can vary on a day-to-day basis.

\
In addition to information from others, information from test results can also carry a cost. If an X-ray is required for a patient, the X-ray machine (and its radiologists) would have to be available at the time of request. The test may then take time to organise, on top of the time it takes for the results to be made available. When information has a certain cost associated with it, clinicians may be more likely to focus on the information that they already have available to them. This 'availability bias' was cited as a cause of cognitive bias in one case study of a patient with an acute myocardial infarction [@schlogl_foreign_2018]. Available information has to also be judged in terms of whether they are 'up to date' for the patient's current condition. It is quite common for clinicians to repeat tests, as such as in one observed case in AICU where a chest X-ray was repeated for a patient to check for an improvement with regards to an edoema. I also observed that seeking a test is usually associated with a particular goal. A test is usually requested to query a particular diagnosis. One example I observed was a request for a D Dimer (test to detect blood clots) where a positive result was actually ‘not diagnostic’ for a particular condition, whilst a negative result was considered ‘more informative.’ This indicates a certain strategic aspect to information seeking that we are yet to fully understand, especially with regards to confidence, given the more simplistic depiction of information seeking in our work and in the extant literature. This also indicates, along with other instances observed, that information seeking had a hypothesis-driven aspect such that clinicians tended to seek specific tests to rule in or rule out a particular differential (once they had at least one key differential in mind).

\
A final aspect of information seeking to note is the role of colleagues, senior staff and other specialists. Information within healthcare settings can be used for two purposes: enhancing general situation awareness and specific diagnostic hypothesis testing. The information that clinicians receive from other medical staff can especially aid with the former of these, as decision making in ED and AICU, among other medical settings, involves necesssary consultation with several colleagues. A consultant may ask the nurse who was seeing the patient during the night for an update, or ask for advice from senior or specialist staff. In both AICU and ED, staff were consistently in contact with staff from other departments (e.g. neurology, surgery, psychiatry). This seemed to not only be for advice seeking, but also for coordination purposes. Put simply, if a patient is experiencing trauma, the Trauma team likely has to be consulted as the patient case falls within their expertise. However, there is important information that can be gleaned from colleagues through this communication process that can be just as valuable as a patient’s test results. In sum, information seeking as an area of study with healthcare is not simply limited to perform physical examinations and tests on the patient (as per our empirical studies), but is much more holistic, as it involves getting appropriate information from the hospital environment and the other clinicians who work there.

## Differential Evaluation

The evaluation of diagnostic differentials in real medical settings is perhaps the largest divergence from our vignette studies. Doctors in both settings were observed to consider, at most, two or three differentials at any given time (in our online study, participants considered around three or four differentials at a time on average, depending on the stage of information seeking). It is worth noting however that actively diagnosing the patient was not observed as much in AICU when compared to ED. This is because patients have usually been staying in AICU for a much longer period of time (on the order of days or weeks), and as such there has been much more information made available about the patient to have formulated a working diagnosis. Diagnosis, in terms of identifying what condition a patient has, is hence not as focal a task for AICU clinicians in their daily practice, instead they tend to focus more on treatment and stabilisation of the patient. Diagnosis not being a focal task could explain the lower number of differentials being considered. It is also worth noting that our experimental work was with a much less experienced cohort compared to those working in AICU and ED, which would likely also affect the number of differentials being considered at any given time (as highlighted by @coderre_diagnostic_2003, who showed that experienced clinicians tended to use pattern recognition and evaluate fewer differentials when compared with novice clinicians).

\
When focusing on diagnosis as observed in ED, clinicians were not considering a list of several differentials as in our empirical studies. The consideration of only two or three differentials at a time has been interpreted as being due to limitations of working memory [@gilhooly_cognitive_1990], especially if clinicians are not using aids or regular note-taking to keep track of the various differentials being considered. There was however a distinction made between competing differentials in terms of their likelihood and severity. A general model of diagnosis, particular in ED, was for clinicians to query a "most likely" primary diagnosis that is most likely whilst simultaneously considering an alternative diagnosis that would be have serious consequences if missed. In erring on the side of caution, the focus was first on seeking information such as tests to rule out this alternative diagnosis, rather than seeking information to confirm the primary diagnosis. In this sense, we capture diagnostic thinking in our task by reflecting that not all diagnostic differentials are equal in terms of likelihood and severity, and that competing differentials lead to different strategies for seeking information that query a given differential.

\
When engaging in discussions with colleagues in both settings however, clinicians were observed to actively consider whether there were any possible differentials that they had missed or not considered. With a regular cadence of communication between clinicians, this prompted consideration of other perspectives and expertise. This meant that clinicians would consult their colleagues to broaden their thinking and remain open-minded. This ensures better team Situation Awareness [@salas_situation_1995] and sharing of mental models [@alby_diagnostic_2015]. In AICU, discussions about cases took place during the morning handovers, which involved a group of around 10 members of staff reviewing each patient one by one. Colleagues were encouraged to be thorough and offer suggestions of any considerations/differentials that could have been missed for each patient. On the other hand, as previously mentioned, a clinician in ED was observed to use pattern recognition to quickly identify if each patient's condition was serious or not. Both of these observations, taken together, indicate that the broadening or narrowing of differentials is dependent on contextual factors. As ED is a busier department (in terms of throughput of patients), there is more of a need to narrow the differentials being considered. Meanwhile, in AICU, as patients stay in AICU over much longer timescales without the same immediate time pressures, clinicians were more encouraged to broaden their diagnostic thinking.

## Discussion

The previous subsections of this chapter have provided observations of key examples of diagnostic uncertainty, information seeking and differential evaluation within real medical settings. To collate these observations together in this subsection, I shall discuss the ways in which theoretical concepts and empirical work conducted in this DPhil emulate real medical practice as well as the areas of real medical practice that future research can focus on.

\
There are aspects of the studies in this thesis that do emulate real medical decisions. For one, situations of uncertainty arise frequently in healthcare, validating its need for further study. Uncertainty arises due to a multitude of factors related to patients, clinicians and the healthcare environment (as found from our systematic scoping review). Patients may present with symptoms that are suggestive of several diagnostic differentials (e.g. chest pain), leading to uncertainty that clinicians seek to resolve by seeking further information from the patient, from other clinicians or from their own examinations and testing. The overall flow of clinician decisional processes tends to follow that depicted in our studies: clinicians first develop an understanding of the patient’s medical history, perform some physical examinations of the patient based on the presenting symptoms and finally perform tests to either confirm their suspected diagnoses or rule out others. Uncertainty can arise from competing diagnoses, particularly when a potential diagnosis is common and hence most likely, whilst another is rarer but more serious if missed. This interplay between what is likely and what is serious was observed frequently in real medical settings. Uncertainty also arises from atypical patient cases, particularly when other comorbidities are involved. These manifest in fairly different patient presentations to the prototypical ‘textbook’ case of a condition. An observed example in ED was a patient who reported vision loss in one eye that was suspected to be a result of Giant Cell Arteritis (GCA, also known as Temporal Arteritis/TA). The type of vision loss that the patient experienced was fairly unusual for a patient with this condition, as it was gradual degradation rather than a sudden loss. In our studies, we sought to balance the emulation of patient conditions that medical students could expect to see in their medical practice, whilst also using some atypicality in the patient’s presentation to prompt diagnostic uncertainty. Based on observations, it can be surmised that real medical decisions can often involve patients who do not fall within the ‘textbook’ definition of a condition. Hence, using such cases is a valid method for simulating diagnostic uncertainty in a controlled experiment.

\
I also note that uncertainty can come from incomplete information. The information available on patients in our studies was limited (by the very design of the experiments), and such situations can also occur in real life too. For example, although the hospital I observed used of an electronic system for recording all patient documentation and scans, such centralisation of information is not always the case in healthcare. This can be especially pertinent in less economically developed nations where there is less access to technology to aid clinicians in their decision making. One paper looking at healthcare handover and communication in India [@humphries_investigating_2018] found that there was a reliance on patients to manage their own documentation, often “poorly recorded on unstructured sheets of paper”. Even within the medical setting I observed, there were differences in how clinicians recorded information on the patient. This led to a few observed situations where there was confusion expressed based on notes that a previous clinician (who had been treating the same patient) recorded being too vague. Clinicians may also rely on verbal reports from the patient as a source of information, but patients can be unreliable, uncooperative or suffering from confusion and unable to produce key information (e.g. describing the nature of their pain). These factors together show how clinicians sometimes have to operate without having all the information they may ideally want to make a decision.

\
Another aspect to note is that our work emulates is how clinicians’ thinking evolves over time with more information. Although the time course of our studies’ cases is much shorter than patient evaluation and treatment in real-life, they do capture (in a condensed fashion) how the receipt of information can change clinicians’ thought processes and their confidence in their decisions. This is where a real strength of this work can be observed, in that diagnosis is not a singular decision but an evolving process that we aimed to capture in our studies. Crucially, we also allow some freedom in our vignette studies for participants to cease information seeking when they deem it appropriate. This allows us to capture differences in approaches to information seeking. One clinician I observed in ED wanted to request a chest X-Ray despite the patient already having a chest MRI. The rationale was to ensure a more complete set of scanning modalities was used as a precautionary measure for the patient, but other doctors may not have done this in the same circumstances. The variability in information seeking was observed between clinicians (i.e. seeking information in a hypothesis-driven manner to rule in or rule out differentials), and we capture this aspect throughout our studies. These tendencies are what we aimed to operationalise more formally using our think-aloud study. There is still more work that can be done to study the sources of these individual differences in decision making, particularly on systematic tendencies toward underconfidence or overconfidence. Differences between clinicians were especially apparent when observing clinicians interact, as there were disagreements over, for example, whether certain tests were needed and how serious a patient was. As mentioned before, although most medical decisions are made by groups rather than individuals, studying individual factors that affect decision making is important when individual tendencies become apparent in a group.

\
There are aspects of real medical practice that can be explored in future work beyond this DPhil. As discussed, many decisions in healthcare are made by groups of clinicians, rather than individuals. In both AICU and ED, I observed that it was common for staff to check their understanding with a colleague so that they did not miss any key considerations had they been working alone. In our studies, we tend to focus on the individual clinician and their own decisional process. Future work could either study how individual decision makers seek consultations/advice from other staff or focus on group confidence during diagnoses (the latter of these was noted as an underexplored area in past research based on our systematic scoping review). I would argue however that our work focusing on the individual decision maker is still important, as groups end up being an amalgamation of individual decision makers. If there are systematic tendencies toward overconfidence or underconfidence on the part of the individual, and a group is comprised of like-minded individuals, then individual tendencies would be amplified in a group (as per past social psychology research on ‘groupthink’: [@moorhead_empirical_1986; @park_review_1990]). In addition, the individual decision making of those leading a shift (e.g. consultant, registrar) can have an impact on how others in the team make decisions. These reasons explain why our work focusing on individual decision-making processes is still important despite the group-based nature of clinical decision making.

\
Another aspect of note is that patient cases tend to take place over much longer timescales than our experimental procedures portray. Patients may be at the hospital for days, weeks or even months at a time. Emulating this longer timescale is difficult within a controlled experiment, but our VR study is useful for showing how patients change over time (albeit on a shortened timescale). Clinicians also have to deal with multiple cases at once, and may have to make multiple attentional shifts between each. In our experiments, participants were able to focus on one patient case at a time. Clinicians are more likely to be interrupted/distracted by other patients when they are under higher cognitive load [@lavie_load_2004]. As one paper in our scoping review showed, interruptions were shown to decrease confidence [@soares_accuracy_2019]. Future work could include paradigms that involve multiple cases being diagnosed at once to investigate how appropriate confidence can be prompted. It was also observed that with more patients to manage at once, clinicians were prone to forgetting certain information or even mistaking one patient with another (which is especially understandable during night shifts). It is in these challenging healthcare environments that prompting information seeking that is appropriate to the clinicians’ current cognitive load could be a promising and important avenue for future work (e.g. prompting clinicians to avoid seeking too much information that they are then not likely to remember later on after seeing other patients).

\
I also note aspects of information seeking that future work could tap into based on the observations. As discussed, information can carry a cost in terms of time and may not always be available when needed. This can decrease confidence if clinicians have to continue with a patient case when they are not able to get all the information they need. Future work can look at how the cost in terms of time (and even money in some cases) affects the decision to seek information. A clinician may have to then decide, for example, whether to proceed without a test or await a test result before doing anything else with the patient. Another aspect of information seeking observed was the unreliability of information at times. In particular, a patient is an important source of information, such as describing the nature of the pain they are experiencing. However, patients may not always be reliable in providing information. For example, they may exaggerate their condition in order to emphasise the stress they are feeling or to receive stronger medication. Patients may also not be proficient in the language that the clinician speaks, leading to difficulties in communication. Information from colleagues may be unreliable as well if they do not have an in-depth understanding of the patient. Finally, tests themselves have a degree of unreliability, as most tests have a specificity and sensitivity level such that there is a likelihood of either a false positive or false negative. This means that clinicians may have to seek another opinion, perform the test again or seek other information. During this thesis, the fine-grained nature of information seeking as it pertains to its cost-benefit and its reliability was not emulated. This is a facet of real medical practice that is again tricky to emulate experimentally but could yield interesting insights into the decisional process.

\
In summary, I observed there to be key aspects of medical decisions as they occur in real practice that we emulated in our empirical studies. Although there are inevitably other characteristics of medical decisions that we do not cover in our work, these can be considered more as opportunities for future work rather than limitations with our current work. We believe there is sizeable scope for future research to delve even further into the cognitive psychology that underpin medical decisions made by clinicians, especially as they play out in everyday healthcare settings. For instance, there is work to be done on how contextual factors impact diagnostic confidence. When reviewing the extant literature studying surgeons' cognitive biases, [@armstrong_cognitive_2023] found that the vast majority of papers only looked at person-based sources of biases, rather than environmental and contextual factors. If a clinician encounters a patient with a broad set of differentials, they may have to seek more information to arrive at a final decision. If however the clinician was also more pressed for time due to other patients requiring attention, this limits the time that they can spend with the patient. This means that the clinician is under a time pressure to make a decision, as well as less of a scope for seeking further information. As discussed previously with an observed ED registrar, a clinician may see patients quickly to identify serious/urgent cases, thereby being consciously less thorough in their decisional process. What this indicates is that clinical reasoning does not have a 'one-size-fits-all' approach that works for all medical situations. Rather, clinical decision making can take many forms and requires clinicians to adapt their approach based on the patient and context. As observed in ICU and ED, real medicine is messy and constantly evolving and, as such, the study of medical decision making should adapt its methodologies and to reflect this.

\
With the observations of real medical practice discussed during this chapter in mind, we shall now discuss the overall findings from the studies within this thesis. We shall start by summarising the empirical results with regards to diagnostic confidence, information seeking and differential evaluation, as well as contextualising these results within the extant literature. We then discuss overall strengths and limitations with the studies conducted, which will provide some avenues for future work to explore. Finally, we will discuss the implications of this work, for cognitive psychology research and for future medical education and practice.
